version: '3'
services:
  burger_orderer:
    build: ./BurgerOrderer
    ports:
      - "8000:8000"
    depends_on:
      - db

  kitchen_view:
    build: ./KitchenView
    ports:
      - "8001:8001" 
    depends_on:
      - db

  menu_store:
    build: ./MenuStore
    ports:
      - "8002:8002"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
